
import React, { ReactNode } from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../styles/globals.css';
import { ThemeProvider } from '@/app/components/themProvider';
import ConvexClientProvider from "./ConvexClientProvider";
import Layout from './components/Layout';

const inter = Inter({ subsets: ['latin'] });


interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <ConvexClientProvider>
         <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
            <Layout> {children} </Layout>
        </ThemeProvider> 
      </ConvexClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
